apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-config
data:
  DEBUG: "True"
  DB_NAME: "messaging_app_db"
  DB_USER: "app_user"
  DB_HOST: "messaging-mysql"
  DB_PORT: "3306"
  ALLOWED_HOSTS: "*,.svc.cluster.local,localhost,127.0.0.1"
